name: Release

on:
    push:
        branches:
            - release

permissions:
    contents: write

jobs:
    release:
        name: Semantic Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Run Semantic Release for each package
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  for dir in packages/*/ ; do
                    cd "$dir"
                    if [ -f "release.config.js" ]; then
                      npx semantic-release --extends ./release.config.js
                    fi
                    cd - > /dev/null
                  done
