name: Publish auto-claim docker images to GCP

on:
    # Trigger for ANY published release
    release:
        types: [published]

    # Also allow manual runs
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag to build and push"
                required: true
                type: string

permissions:
    contents: read
    id-token: write

jobs:
    docker-release-auto-claim:
        # THIS IS THE KEY: It filters the jobs to run ONLY for matching tags
        # OR if the workflow was triggered manually.
        if: startsWith(github.event.release.tag_name, 'bridge-hub-auto-claim@') || github.event_name == 'workflow_dispatch'

        uses: 0xPolygon/pipelines/.github/workflows/gcp_pipeline_release_image.yaml@main

        with:
            image_name: "bridge-hub-auto-claim"
            dockerfile_path: Dockerfile.autoclaim
            # Use the tag from the manual input OR from the release event that triggered the run
            image_tag: ${{ inputs.tag || github.event.release.tag_name }}
            checkout_ref: ${{ inputs.tag || github.event.release.tag_name }}
